version: '3.9'
services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: syonet
      POSTGRES_DB: financeiro
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

  app:
    build: ./financeiro-api
    container_name: backend-container
    depends_on:
      - db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/financeiro
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: syonet
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./financeiro-web
    container_name: frontend-container
    ports:
      - 3000:3000
    depends_on:
      - app

volumes:
  postgres-data:
